"""empty message

Revision ID: 873cf8b0faaa
Revises: b0394f6c15f0
Create Date: 2021-03-08 17:33:06.364171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873cf8b0faaa'
down_revision = 'b0394f6c15f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
