"""empty message

Revision ID: b0394f6c15f0
Revises: 476c92791b0b
Create Date: 2021-03-08 16:03:51.335855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0394f6c15f0'
down_revision = '476c92791b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('shows_venues_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'venues_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venues_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venues_id_fkey', 'shows', 'venues', ['venues_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
